apiVersion: v1
kind: Service
metadata:
  name: desafio-devops-service
  namespace: desafio-devops-namespace
spec:
  selector:
    app: desafio-devops-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP